# -*- coding: utf-8 -*-
"""CSDS 447.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-NVpA7S6Y5oJRWnnRGCBKLeByUq5hVFA
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# 1. DATA DEFINITIONS

# Colors for the chart
COLORS = ['#cccccc', '#a6cee3', '#1f78b4', '#b2df8a'] # World, US, Flux, SD

# --- FLUX MODEL DATA ---
flux_race = {
    "White": 0.4939, "Black": 0.1681, "South/SE Asian": 0.0357,
    "East Asian": 0.1345, "Middle Eastern": 0.0967, "Latino": 0.0710
}
flux_gender = {"Male": 0.9116, "Female": 0.0884}
flux_age = {"0-19": 0.0008, "20-39": 0.9759, "40-59": 0.0232, "60+": 0.0}

# --- STABLE DIFFUSION DATA ---
sd_race = {
    "White": 0.5122, "Black": 0.1162, "South/SE Asian": 0.0185,
    "East Asian": 0.1967, "Middle Eastern": 0.1096, "Latino": 0.0469
}
sd_gender = {"Male": 0.9551, "Female": 0.0449}
sd_age = {"0-19": 0.0, "20-39": 0.9716, "40-59": 0.0284, "60+": 0.0}

# --- US DATA (Vintage 2024 Estimates / 2020 Census MENA) ---
# Note: These may not sum to exactly 1.0 due to 'Other', 'Mixed', and 'Indigenous' categories not listed.
us_race = {
    "White": 0.581,          # Non-Hispanic White alone
    "Black": 0.125,
    "South/SE Asian": 0.047, # Indian, Filipino, Vietnamese, etc.
    "East Asian": 0.027,     # Chinese, Korean, Japanese
    "Middle Eastern": 0.012, # ~1.2% MENA (distinct from White)
    "Latino": 0.195          # Hispanic/Latino
}
us_gender = {"Male": 0.495, "Female": 0.505}
us_age = {"0-19": 0.25, "20-39": 0.27, "40-59": 0.25, "60+": 0.23}

# --- WORLD DATA (UN/World Bank 2024 Estimates) ---
world_race = {
    "White": 0.13,
    "Black": 0.15,
    "South/SE Asian": 0.34,
    "East Asian": 0.21,
    "Middle Eastern": 0.07,
    "Latino": 0.085
}
world_gender = {"Male": 0.502, "Female": 0.498}
world_age = {"0-19": 0.33, "20-39": 0.29, "40-59": 0.24, "60+": 0.14}


# 2. DATA INTEGRITY CHECKERS

def check_distribution(name, data):
    """Checks if the values in a dictionary sum to 1.0 (with slight tolerance)."""
    total = sum(data.values())
    is_valid = 0.95 <= total <= 1.05 # 5% tolerance for rounding

    status = "PASS" if is_valid else "WARNING"
    print(f"[{status}] {name}: Sum = {total:.4f}")

    if not is_valid:
        missing = 1.0 - total
        print(f"    -> Note: Data deviates by {missing:.4f}. (Likely 'Mixed/Other/Indigenous' categories)")

print("--- RUNNING DATA INTEGRITY CHECKS ---")
check_distribution("Flux Race", flux_race)
check_distribution("Flux Gender", flux_gender)
check_distribution("Flux Age", flux_age)
print("-" * 30)
check_distribution("SD Race", sd_race)
check_distribution("SD Gender", sd_gender)
check_distribution("SD Age", sd_age)
print("-" * 30)
check_distribution("US Race", us_race)
check_distribution("US Gender", us_gender)
check_distribution("US Age", us_age)
print("-" * 30)
check_distribution("World Race", world_race)
check_distribution("World Gender", world_gender)
check_distribution("World Age", world_age)
print("--- CHECKS COMPLETE ---\n")


# 3. DATAFRAME CONSTRUCTION

def create_df(world, us, flux, sd, categories):
    data = {
        "Category": [],
        "Percentage": [],
        "Source": []
    }

    for cat in categories:
        data["Category"].extend([cat] * 4)
        data["Source"].extend(["World", "US", "Flux", "Stable Diffusion"])
        data["Percentage"].extend([
            world.get(cat, 0),
            us.get(cat, 0),
            flux.get(cat, 0),
            sd.get(cat, 0)
        ])

    return pd.DataFrame(data)

# Race DataFrame
race_cats = ["White", "Black", "South/SE Asian", "East Asian", "Middle Eastern", "Latino"]
df_race = create_df(world_race, us_race, flux_race, sd_race, race_cats)

# Gender DataFrame
gender_cats = ["Male", "Female"]
df_gender = create_df(world_gender, us_gender, flux_gender, sd_gender, gender_cats)

# Age DataFrame
age_cats = ["0-19", "20-39", "40-59", "60+"]
df_age = create_df(world_age, us_age, flux_age, sd_age, age_cats)


# 4. PLOTTING FUNCTION

def plot_grouped_bar(df, title, filename):
    categories = df['Category'].unique()
    sources = df['Source'].unique()

    x = np.arange(len(categories))
    width = 0.2  # Width of each bar

    fig, ax = plt.subplots(figsize=(14, 7))

    for i, source in enumerate(sources):
        vals = [df[(df['Source'] == source) & (df['Category'] == cat)]['Percentage'].values[0] for cat in categories]

        pos = x + (i - 1.5) * width

        rects = ax.bar(pos, vals, width, label=source, color=COLORS[i], edgecolor='white', linewidth=0.5)

        ax.bar_label(rects, fmt='%.2f', padding=3, fontsize=9, rotation=90)

    ax.set_ylabel('Proportion (0.0 - 1.0)', fontsize=12)
    ax.set_title(title, fontsize=14, pad=20, fontweight='bold')
    ax.set_xticks(x)
    ax.set_xticklabels(categories, fontsize=11)

    # Add Grid
    ax.yaxis.grid(True, linestyle='--', alpha=0.7)

    # Legend
    ax.legend(fontsize=10, loc='upper right')

    plt.tight_layout()
    plt.savefig(filename, dpi=300)
    print(f"Generated chart: {filename}")
    plt.close()

# 5. GENERATE PLOTS

plot_grouped_bar(df_race, 'Race Distribution: World vs US vs Flux vs SD', 'race_bias_analysis.png')
plot_grouped_bar(df_gender, 'Gender Distribution: World vs US vs Flux vs SD', 'gender_bias_analysis.png')
plot_grouped_bar(df_age, 'Age Distribution: World vs US vs Flux vs SDs', 'age_bias_analysis.png')